### PR TITLE
Export ko.utils.cloneNodes

### PR DESCRIPTION
**Pull request by dregre**
`ko.utils.cloneNodes()` is a pretty useful method, but is unexported; let's export it.

### CODE REVIEW

**Comment by mbest** [comment]
If you add a spec to spec/utilsDomBehaviors.js, I'll merge this.

**Comment by dregre** [comment]
Thanks @mbest for the quick reply!  I've added the spec.
I've rebased so be sure to reset locally.

**Comment by codymullins** [comment]
@dregre typically you should not rebase branches that have been made "public"

**Comment by dregre** [comment]
My bad, force of habit @codymullins
The other commit was a one-liner, should be ok if it makes its way back to the commit history.

**Pull request merged**
