### PR TITLE
Computed observable memory leak fix

### PR DESCRIPTION
**Pull request by coot**
The dispose method of `ko.computed` should release a link to the owner (vel `evaluatorFunctionTarget`).

### CODE REVIEW

**Comment by mbest** [comment]
The test updates show that it's currently possible to "write" to a disposed computed observable, and the changes here could cause that to fail.

**Comment by chrisknoll** [comment]
I understand we wouldn't want to break existing functionality, but shouldn't the case where you access a disposed observable be considered invalid?  Shouldn't disposed mean it's gone?

**Comment by mbest** [comment]
Reading a disposed computed is definitely supported and used internally in Knockout. Writing to a disposed computed, though, doesn't seem to have much point. So I'm okay with saying it's not supported. Perhaps, then it should throw an error rather than failing in some unknown way.

**Comment by coot** [comment]
Closing because of inactivity.

**Pull request closed without merging**
