### PR TITLE
Improved headings and snippet readability

### PR DESCRIPTION
**Pull request by PandelisZ**
Slight improvement to overall readability of the readme. Made the headings render as headings and added the `sh` tag to the snippets so they are rendered with some padding on GitHub

### CODE REVIEW

**Comment by mbest** [comment]
Most of this is good, but your changes in the build section have messed up the indentation.

Before:

image

After:

image

**Comment by PandelisZ** [comment]
Oh whoops sorry I missed this thought I had it fixed.

**Comment by PandelisZ** [comment]
Unfortunately the GitHub markdown flavour doesn't play nicely with indenting paragraphs. Going to have to look into this further. The triple \` code highlighting feature seems to default to just no indentation.

**Comment by PandelisZ** [comment]
ok @mbest i got it now I think, triple spaces are our friend apparently
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#alt-h2

screen shot 2017-05-22 at 11 52 59

If this is ok I can flatten these messy commits.

**Comment by mbest** [comment]
Looks good.

**Pull request merged**
