### PR TITLE
Update selectedOptions binding to not reset option selected status if not necessary

### PR DESCRIPTION
**Pull request by srd8580**
It causes the IE issue outlined here:
http://stackoverflow.com/questions/28683205/knockoutjs-multiselect-issue-in-internet-explorer

No side effects detected.

### CODE REVIEW

**Comment by SteveSanderson** [comment]
Thanks for this!

Any chance you could add a test to show that this makes a difference? Otherwise this behavior could get lost in a future update, since looking at the code it's not obvious that your change would cause a change of behaviour.

**Comment by srd8580** [comment]
Hi Steve, thanks for looking at this.  

Unfortunately, I'm at a loss to create a Jasmine test for this as you implied, there actually is no change in behaviour at all.  The issue this change resolves is purely performance related.  I am unfortunately still supporting IE8, and the performance improvement on multi-select elements with a large number of options is dramatic with this change in IE8.  It goes virtually unnoticed in other browsers, however.

I would happily put together a JS Fiddle if it would help getting it merged?

**Comment by srd8580** [comment]
I almost forgot, this JSFiddle http://jsfiddle.net/unp9j9dc/1 shows a UI "bounce" issue in IE also, again, not reproducible in Jasmine or non-IE browsers.

**Comment by mbest** [comment]
I decided to fix this a different way (see the attached commit) when I noticed that Chrome also changes the scroll position when updating the `<select>` from the view model. I ended up including a similar check as yours, though, to prevent the `<select>` from flashing in IE.

**Comment by srd8580** [comment]
This is great guys!  Thanks a lot.

**Pull request closed without merging**
