### PR TITLE
Add typescript types

### PR DESCRIPTION
**Pull request by SomaticIT**
This Pull Request is created to include `TypeScript` types into `knockout` repository. This is related to #2353. 

This allows the `TypeScript` compiler to automatically find the `knockout` types when using option `moduleResolution: "node"`.

This includes:
 * Types definitions taken from [typed-contrib](https://github.com/typed-contrib/knockout) and revised for `TypeScript` 2+
 * Types tests taken from [typed-contrib](https://github.com/typed-contrib/knockout)
* `Grunt` task to test types automatically
* `package.json` configuration to help `tsc` finding the types.

### CODE REVIEW

**Comment by IanYates** [comment]
This looks really good! :)

Am I right in understanding that we can add tests to the test-module.ts file to verify things that should be able to compile?

Is there a way to test things that should *not* be able to compile?

**Comment by SomaticIT** [comment]
For now, you need to include your tests in both `test-module.ts` and `test-global.ts`.
I think now that TypeScript support `UMD` module definition, we could only keep `test-module.ts`.
I have to search more on this.

Testing things which should not compile is a really good question! :) 
I do not have a solution right now.

I think we can add a folder `failing` which contains a file containing __X__ typing errors.
We then add a task in Gruntfile which executes `tsc` and count compiler errors.

But it may not be a good solution because it invoke a lot of stuff for few tests and the number of errors could vary depending on the TypeScript compiler.

Let me know if you have another idea.

**Comment by IanYates** [comment]
I don't have another idea yet unfortunately.  I enjoy trying to extend TS definitions to avoid things like any, etc as much as possible.  After a quick browse through what you've posted I think yours as pretty good.

My hope is that, when I get some time, I can try them in our project and see what fails.  That'll lead to a PR to amend them in the future, but that's weeks away.

I've also volunteered to do a task similar to yours for another JS library (fabricJS) which has had a few people try various ways of making definitions in definitely typed.  I've been improving an old copy of those definitions as I've been using the library on and off over a few months.  Unfortunately someone then replaced them completely in definitely typed with something else that was completely incompatible but not any better.  So the project maintainer wants someone to do something official :)

A big part of TS is catching things that might look OK but really are incorrect (as you know already.. pointing this out for the spectators).  That's why I was keen to find out if there was a good method for deliberately failing to compile.  When I get to that project in a week or so I'll see if I find a way of testing for that and let you know.

**Comment by mbest** [comment]
I've gone through this and made some updates. See 70b7d7c9bfd2b9a1201. Please look over them and let me know if you find any problems. I'm still pretty new to TypeScript, so I may have missed something.

**Comment by michaelaird** [comment]
I think having the type definitions in the knockout repository is great. I would suggest reaching out to the people who have contributed to the DefinitelyTyped definitions (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/knockout/index.d.ts) for input.

Also, if the typescript definitions are going to be maintained as part of the repo, they should probably be removed from DefinitelyTyped and replace this package: https://www.npmjs.com/package/@types/knockout

**Comment by mbest** [comment]
Thanks for the input @michaelaird. Would it possible for you to try out the new type definitions?

Also any of the contributors from DefinatelyTyped: @borisyankov, @Igorbek, @moonpyk, @EnableSoftware, @BenjaminEckardt, @ffMathy.

**Comment by codymullins** [comment]
I'll add it to our project and see what happens.

**Comment by SomaticIT** [comment]
I'll review your updates and add it to our projects to see if they match.

**Comment by codymullins** [comment]
I guess I didn't really pay much attention, but this is most definitely not an easy update. We're using the type definitions from DefinitelyTyped, which are significantly different. I suspect there are going to be a lot of people in this same situation who are going to want to know what to change to match, unless we can determine what can remain the same.

**Comment by mbest** [comment]
It looks like the DefinitelyTyped declaration file declares all of the interfaces globally, which is not the recommended approach.

**Comment by michaelaird** [comment]
The one thing I beg of you is please do not replicate this bit of blasphemy

```
interface KnockoutExtensionFunctions {
    [key: string]: any;
}
```

It got added to the DefinitelyType definitions awhile back and has accounted for untold # of errors and bugs. It basically says that any identifier you tack onto an Observable or ComputedObservable is valid and ```any```. This means that any kind of typo or mistake passes the TypeScript compiler and only blows up at runtime. :( :( :(

**Comment by SomaticIT** [comment]
@codymullins 

I worked on new types for `knockout.mapping`: https://github.com/typed-contrib/knockout.mapping
I also have a local version for `knockout.validation`.

I wait this types to be fully validated before submitting the dependent types.

**Comment by mbest** [comment]
I've add #2362 with my updates.

**Comment by mbest** [comment]
Replaced by #2362

**Pull request closed without merging**
