### PR TITLE
Version 3.4.2 updates

### PR DESCRIPTION
**Pull request by mbest**
There are a number of bug reports concerning deferred updates that I think would be good to fix and release earlier than we could get out a 3.5.0 version.

#2174 #2163 #1835 #1943 

#2197

### CODE REVIEW

**Comment by mbest** [comment]
I've added another fix regarding computeds and deferred updates (#2197). If nothing serious comes up, I'll plan to release this in a week or so.

**Comment by codymullins** [comment]
@mbest I'll pull down the latest and do more testing.

**Comment by mbest** [comment]
Publish to:
- [ ] NPM
- [ ] CDNJS (should be automatic; check up on it)
- [ ] Microsoft Ajax CDN
- [ ] NuGet
- [ ] jsfiddle

**Comment by mbest** [comment]
@PeterDaveHello Can you update CDNJS with the latest (https://github.com/knockout/knockout/releases/tag/v3.4.2)?

**Comment by mbest** [comment]
@oskarkrawczyk Can you add 3.4.2 to jsfiddle?

**Comment by PeterDaveHello** [comment]
@mbest updated, if you could remove `-latest` in the file name next time, it could be automatically updated.

**Comment by mbest** [comment]
@PeterDaveHello Are you referring to the npm package?

**Comment by PeterDaveHello** [comment]
@mbest yes as you can see on https://cdnjs.com/libraries/knockout

**Pull request merged**
