### PR TITLE
ko.when returns predicate truthy value as callback 1st parameter

### PR DESCRIPTION
**Pull request by miellaby**
see discussion in https://github.com/knockout/knockout/pull/2113 comments

### CODE REVIEW

**Comment by mbest** [comment]
Thanks.

**Comment by miellaby** [comment]
next improvement: not wrapping an already subscribeable into a computed?

**Comment by mbest** [comment]
> not wrapping an already subscribeable into a computed?

I don't think it's necessary, and it would make the code a bit more complex.

**Comment by miellaby** [comment]
Now, I'm thinking... ko.when should accept a second `owner` argument for consistency with the remaining JS API. It would be passed to the computed.

**Comment by mbest** [comment]
> Is it OK to pass an observable as a computed read function?

Yes,

**Comment by mbest** [comment]
> ko.when should accept a second owner argument

It probably makes sense to use the existing `context` parameter for the computed. I'll work on that.

**Pull request merged**
