### PR TITLE
Component afterRender functionality

### PR DESCRIPTION
**Pull request by krishnaglick**
Components need a way to run functionality after they're done rendering.
Here's my solution

### CODE REVIEW

**Comment by Domitnator** [comment]
When can we expect this feature to be commited to the master branch? Really looking forward to this one!

**Comment by caseyWebb** [comment]
Isn't the `viewModel` executed after render?

**Comment by rameshr1986** [comment]
Hi all is there a way to identify the page transition when all the subcomponents are loaded

**Comment by rameshr1986** [comment]
I meant to show the page once all its components and sub components are loaded

**Pull request closed without merging**
