### PR TITLE
Adding the preferJQueryEvents option as a way to avoid using jquery eventing in knockout.

### PR DESCRIPTION
**Pull request by dzearing**
Usage:
```html
<head>
    <script src="knockout.js"></script>
    <script type="text/javascript">
        ko.options.preferJQueryEvents = false;
    </script>
   <script src="jquery.js"></script>
</head>
```
// Now all events fired from knockout should not have jquery in the callstack. It is assumed the option is set before applyBindings is called.

### CODE REVIEW

**Comment by SteveSanderson** [comment]
Thanks for this!

Is it possible to add a test for this change? When we run the tests, we do so both with and without jQuery, so it would make sense to have a test that we don't get jQuery event behaviour in the presence of this flag.

**Comment by mbest** [comment]
Should this option also affect `ko.utils.triggerEvent`?

**Comment by dzearing** [comment]
I'll look into the tests. 

Good call @mbest. I will take a look.

**Comment by dzearing** [comment]
Added a test to validate the option locks out jquery eventing.

Updated trigger.

I ran this with runner.html and runner.html?jquery=1, and validated it works in both cases. I'm not sure of a clever way to distinguish trigger behavior coming from jquery vs not.

**Comment by dzearing** [comment]
ping!

**Comment by stalniy** [comment]
It's better to use direct terminology. I'd like to see `useJqueryEvents = true/false` instead of `noJqueryEvents = true/false`.

At least it's hard to understand for my brain the meaning of `noJqueryEvents = false`

**Comment by brianmhunt** [comment]
I agree with @stalniy – The double-negative is too much for my brain. :)

**Comment by dzearing** [comment]
Renamed to "useJQueryEventing". Good call.

**Comment by mbest** [comment]
When I was reading your comment, I at first thought it said "everything" instead of "eventing".

**Comment by dzearing** [comment]
Happy to rename, just give me something everyone is satisified with, so we can finish this off. I can change to useJqueryEvents if it is more straightforward. In my opinion options are always going to be a little mysterious to use, even if named something completely innocent, so naming it useJQueryEvents vs useJqueryEventsWhenAvailable is still going to require a little digging to understand what that implies. It's requires a little digging just to even know that jquery is being referenced from knockout in the first place, I would have not guessed that.

**Comment by brianmhunt** [comment]
@dzearing How does `preferJQueryEvents` ring with you?

**Comment by dzearing** [comment]
Done, I like it.

**Comment by dzearing** [comment]
Any other feedback?

**Comment by SteveSanderson** [comment]
Looks great! And thanks for making the option name change - sounds ideal now.

Merged. I think the other core team members will have seen this by now (since @mbest and @brianmhunt have commented here) but if not and any of you have concerns please let us know.

**Comment by rniemeyer** [comment]
I thought that this one seemed fine. I would generally prefer new options to match the default/current behavior when undefined/falsey, but did agree that the double-negative was confusing.

**Comment by mbest** [comment]
If we'd rather have an option that defaults to `false`, how about `useOnlyNativeEvents`?

**Comment by rniemeyer** [comment]
>  If we'd rather have an option that defaults to false, how about useOnlyNativeEvents?

+1

**Comment by rniemeyer** [comment]
Note: option was updated to `useOnlyNativeEvents` here: 09b9e93f29a7ec7a5282fe9deb2a750d9e48f8f4

**Comment by brianmhunt** [comment]
@rniemeyer I updated the title too, just in case someone wanders onto this :)

**Pull request merged**
