### PR TITLE
Support namespaced attributes with default attr binding

### PR DESCRIPTION
**Pull request by rampion**
When using knockout to create manage SVG or XML nodes, it is sometimes desirable to have it manage attributes from specific namespaces.  For example, links in SVG documents use the `xlink` namespace. Currently, the `attr` binding doesn't support attribute namespaces, as can be seen in [this fiddle](http://jsfiddle.net/ZghP7/).  The hardcoded `xlink:href` works as a link, while the `xlink:href` attribute created by knockout doesn't, because it doesn't have the right namespace.

This could certainly be compensated for by creating a `attr-ns` binding just to handle namespaced attributes, however not only would this have a high degree of code repetition, but this breaks the similarity between hardcoded attribute and attributes defined by `attr`. The HTML parser is smart enough to figure out which attributes have namespaces, why shouldn't knockout do the same? The DOM provides the `Node.lookupNamespaceURI()`, `Node.setAttributeNS()` and `Node.removeAttributeNS()` methods just for this purpose.

This pull request uses these API functions to add namespace support to the default `attr` binding. It also adds a test to the spec to check that namespace support is working properly.

ref: http://stackoverflow.com/questions/18083723/how-can-i-get-knockout-js-to-set-the-namespaceuri-for-attributes

### CODE REVIEW

**Comment by troyschneringer** [comment]
+1

**Comment by krnlde** [comment]
It's been two, almost three years, since that feature was requested. What is happening? Why is this PR not merged yet? Big bump!

**Comment by brianmhunt** [comment]
Submit a PR and I'll merge this against tko.binding.core/src/attr.js

**Comment by rampion** [comment]
@brianmhunt I would love to, but I can't seem to run tko.binding.core's tests right now:

```
root@5b0632d0c3f6:~/tko.binding.core# gulp test --once
[00:53:48] Using gulpfile ~/tko.binding.core/gulpfile.js
[00:53:48] Starting 'test'...
08 05 2017 00:53:48.215:WARN [watcher]: Pattern "/root/tko.binding.core/spec/helpers/setup.js" does not match any file
.
08 05 2017 00:54:18.191:INFO [karma]: Karma v1.7.0 server started at http://0.0.0.0:7777/
08 05 2017 00:54:18.194:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 05 2017 00:54:18.227:INFO [launcher]: Starting browser PhantomJS
08 05 2017 00:54:18.690:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket IY4nCyPIs2VTHKBrAAAA with id 7442831
4
PhantomJS 2.1.1 (Linux 0.0.0)  🚨  Error: SyntaxError: Unexpected token 'const'
at http://localhost:7777/base/spec/attrBehaviors.js?48d2f00b2ac970646673804383217f610e500667:3919
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at spec/attrBehaviors.js:3919


 🏁  Run complete.
...
```

I'm not sure what your in the configuration chain is causing `const` to be emitted in the code, but AFAIK, PhantomJS doesn't support ES6, so this is breaking my ability to run tests.

Tell me how I can test my PR, and I'll gladly submit it.

**Comment by brianmhunt** [comment]
Thanks @rampion – I just broke the testing – we're moving to a monorepo (at knockou/tko) so there are a few hitches, like this, as I nail tooling down.

You can either checkout from a few days ago (where testing should work) or give me a couple days and I'll have it working – it'll be in the monorepo at github.com:knockout/tko's packages/tko.binding.core directory.

Please ping me if I haven't gotten back by next week!  Thanks @rampion

**Comment by krnlde** [comment]
Can I help somehow?

**Comment by mbest** [comment]
Turns out some browsers (Chrome) don't like it when you use `setAttributeNS(null,..` instead of `setAttribute`.

**Pull request merged**
