### PR TITLE
Execute async components.get callbacks in batches

### PR DESCRIPTION
**Pull request by AdamWillden**
Takes a step towards fixing #1638 

[This still needs unit testing however.](https://github.com/knockout/knockout/issues/1638#issuecomment-67704245)

### CODE REVIEW

**Comment by AdamWillden** [comment]
Just adding a note here to read the comments on #1638 regarding animation frame batching. Might be a preferred method to batching. Although my poor in-application 'test' showed showed animation frame to be slower slower than batching I think someone needs to create a simpler performance test online to definitively compare them.

**Comment by brianmhunt** [comment]
Thanks @AdamWillden – I was mulling this a bit, too.

There are quite a few performance comparisons between `requestAnimationFrame` and `setTimeout`, all seeming to show the prior being more performant e.g. http://jsperf.com/requestanimationframe-vs-setinterval-loop/7

I feel like `requestAnimationFrame` is preferable because it is designed to ["deal with things at the most convenient time for the browser"](http://calendar.perfplanet.com/2013/the-runtime-performance-checklist/), meaning it:

1. Does not draw items while they are not visible in the DOM;
2. Does not draw until the browser is ready (i.e. after any repaints, so no duplication before/after);
3. Slows the animation speed while the browser/tab is not focused.

... which will make CPU usage more efficient in general, and therefore also improve battery life. Where the reflows/repaints are complex, it could also dramatically improve performance over a setTimeout.

While experimenting with [knockout-fast-foreach](/brianmhunt/knockout-fast-foreach) I noticed that, where possible, one ought to batch `requestAnimationFrame` as done in this PR, otherwise there is a significant function-call overhead (i.e. iterating over an array of items in one frame is faster than `requestAnimationFrame` iterating over its list of callbacks).

Which is all to say, I think (but am always open to being shown to be wrong :)) that both batching and `requestAnimationFrame` could be used together and that would seem to be the best option.

@AdamWillden - I think it would be interesting to see what sort of performance you see if you combine batching with `requestAnimationFrame`.

**Comment by AdamWillden** [comment]
@brianmhunt ah yeah that sounds like the best approach! Good thinking. 

I do agree the `requestAnimationFrame ` method should be better which is why I don't trust my poor man's test.

In the next week or so I'll combine the two methods and update this PR :-)

**Comment by brianmhunt** [comment]
Awesome, thanks @AdamWillden

**Comment by AdamWillden** [comment]
Right @brianmhunt I've made the changes. Seems to work (not bothered comparing performance to previous). Still needs tests.

**Comment by brianmhunt** [comment]
Awesome, thanks @AdamWillden

**Comment by mbest** [comment]
#1738 now handles this.

**Pull request closed without merging**
