### PR TITLE
Added predicate object match for arrayFirst like lodash find()

### PR DESCRIPTION
**Pull request by mblarsen**
E.g. 

```
ko.utils.arrayFirst(this.categories(), { id: 4 });
```

This is useful for determining of new data should be added to an array.

Specs, updated.

### CODE REVIEW

**Comment by mblarsen** [comment]
@rniemeyer I think I managed to branch it correctly #2071

Thanks for the help 👍

**Comment by mbest** [comment]
In general, the `ko.utils` functions are meant to support Knockout itself. Thus I don't think this addition is important to include in `ko.utils`.

**Comment by mblarsen** [comment]
I kind of got that feeling reading the code. 👍

**Comment by miellaby** [comment]
@mblarsen you could transform your code in a tool returning a arrayFirst compatible closure. usage: ` ko.utils.arrayFirst(this.categories(), matcher({ id: 4 })); `

**Comment by mblarsen** [comment]
@miellaby good point. This seem to work https://gist.github.com/mblarsen/b9cc9ae0086e8eb07c78f5745afc783f

**Pull request closed without merging**
