### PR TITLE
Consistent this keywork context for ko.utils.array functions

### PR DESCRIPTION
**Pull request by garrypas**
Consistent this keywork context for ko.utils.array functions #1482

### CODE REVIEW

**Comment by brianmhunt** [comment]
Looks good --- do we need tests- the results of this PR *seem* fairly apparent.

What happens when `this` is undefined (as it often would be)? Anything nefarious on any browsers?

**Comment by garrypas** [comment]
I tested it in IE6-IE11 and Chrome and the behaviour is consistent with arrayFirst and behaves the same across these browsers - if a third argument is supplied it is used, otherwise 'this' defaults to the global context.

**Comment by SteveSanderson** [comment]
Looks good - thanks for contributing! I'd be happy to have these changes.

Would you add tests to the pull request?

**Comment by mbest** [comment]
I think we should be cautious about making this change, since a direct function call is generally much faster than using `call`.

**Comment by mbest** [comment]
Merged as 62d568379d7d690a677793d4a851e52816fa6ab9 and 068a0417e215d61eb40381c0f18b564a03254b77

**Pull request closed without merging**
