### PR TITLE
Documentation updates for 3.4.0

### PR DESCRIPTION
**Pull request by mbest**
All of the 3.4.0 updates can go in here (although large updates might be better handled in a sub-branch first).

  - [x] Add note about `ko.options.useOnlyNativeEvents` to some or all pages that describe features that use events: `event`, `click`, `submit`, `value`, `checked`, `textInput`, `selectedOptions`, `hasFocus`.
  - [x] `ko.onError` to catch errors from async code. I'm not sure if needs its own page or should be added to the appropriate pages (`event` binding, components, rate-limit, deferred updates, etc.).
  - [x] Observable Array: `sort` and `reverse` return the `observableArray` and not the `Array`.
  - [x] New page for deferred updates. Possible links from other pages (such as where rate-limiting is already mentioned).
  - [x] Update notes on component `synchronous` option. (The option is not needed anymore to prevent multiple DOM reflows.)
  - [x] `ko.tasks`
  - [x] `ko.isPureComputed`
  - [x] Add Edge to supported browsers.

### CODE REVIEW

**Comment by brianmhunt** [comment]
Should we also document `ko.tasks`?

**Comment by brianmhunt** [comment]
Just for ease of reference, two cases should probably be documented because they keep coming up:

1. #1759  --  the hoisting of comments out of `<table>` tags
2. #914 -- `beforeChange` subscription or a change event with the new + old value

Not that these need to go in for 3.4, just thought to note them while we're at it. :grin:

**Comment by mbest** [comment]
> Should we also document ko.tasks?

Yeah, I've added it to the list and am working on it now.

**Comment by mbest** [comment]
I've finally put together the deferred updates documentation.

**Comment by mbest** [comment]
The only Doc item left is `ko.onError`. Any takers, @SteveSanderson, @brianmhunt, @rniemeyer?

**Comment by brianmhunt** [comment]
I'm happy to write the `onError` docs but I can't commit to a timeline right now (probably 2 weeks, give or take)– if someone else wants to pick it up sooner that's super, too. :)

**Comment by rniemeyer** [comment]
I can take `onError` docs

**Comment by mbest** [comment]
Great, @rniemeyer!

**Comment by brianmhunt** [comment]
:+1: @rniemeyer

**Comment by mbest** [comment]
Thanks, Ryan. If there are no complaints, we can consider the 3.4.0 documentation complete.

**Pull request merged**
