### PR TITLE
Add 'input' binding for real-time updates from text fields

### PR DESCRIPTION
**Pull request by mbest**
The `value` binding documentation includes examples of `valueUpdate` options (`keyup`, `keypress`, and `afterkeydown`) and recommends `afterkeydown` as the best choice to keep the view model updated in real-time. But in modern browsers, `input` is actually the best choice since it fires for changes from mouse events (such as from the context menu or drag-and-drop).

I propose that we present the `input` event as the preferred option for real-time updates. In browsers that don't support `input`, we can simulate it using `afterkeydown` and/or `propertychange`.

In the meantime, we should add `input` as a suggested option in the documentation.

### CODE REVIEW

**Comment by MaleDong** [comment]
Hello:

I tested "input" on IE8,7,6. And I wanna know what process we are now? And you said earlier that we can consider using "onpropertyChanged" event (ONLY FOR IE). So is that OK?

PS：Of course I know that it won't be an easy task to support all kinds of browsers……Hmmmmm……If we can support more, that'd be better;)

**Comment by mbest** [comment]
@MaleDong, Knockout includes the `textInput` binding that does what you're looking for.

**Comment by MaleDong** [comment]
Well……Is that the latest version that has the property?
Any examples on your official website? I didn't find anything about that?

**Comment by mbest** [comment]
http://knockoutjs.com/documentation/textinput-binding.html

**Comment by alundiak** [comment]
There are 2 items I'm wondering:
1) According best practices we better use camelCase whenever we can. So I would say to have only `textInput`
2) From consistency and standard prospective, I would say we have to have standard following.
So following this behavior, we have to have aliases for rest bindingsHandlers `selectedOptions`, `checkedValue`, `uniqueName` ?. 

IMHO I don't need aliases, I would reduce amount code and got rid of aliases features. For me camelCase rule has bigger priority.

@mbest what do you think? Is this aliasing is the final approach that KO will use and follow?

**Pull request merged**
