### PR TITLE
If a part of a Binding is "undefined" knockout should catch the excep…

### PR DESCRIPTION
**Pull request by jogibear9988**
…tion

I've fixed this in my fork like this! Maybe it will be possible to create a parameter where the template of the value function could be modified?

### CODE REVIEW

**Comment by mbest** [comment]
Thanks for the suggestion. Perhaps we could add a `bindingOptions` setting for it.

You might also be able to do this through a preprocessor.

**Comment by jogibear9988** [comment]
any news to this?

**Comment by jogibear9988** [comment]
hello? should i upload a new request?

**Comment by jogibear9988** [comment]
new patch : #2177

**Pull request closed without merging**
